### ISSUE TITLE
Grab data from newsapi.org. 

### ISSUE THREAD

**Issue by Landon345** [AseckOben/news-website#3]
This is done by going to https://newsapi.org/ and making an account. Then login and get your api key. We want to put the api key into a .env file so that it stays secret. Then we can access it using process.env.[variable_name].

**Comment by AseckOben** [comment]
Alright I remember how to use env file and all that.

**Comment by AseckOben** [comment]
Hi bro, I got the API key. I saved it in the .env am sure we will have to
call the process.env.[variable_name]. in the app.tsx before i hide and
commit the .env file.

**Comment by Landon345** [comment]
Look, we don't want to commit the .env file to github, but yeah, otherwise
nice job. You can switch to the branch that I made by doing "git checkout
fetch-data". I made it so that it fetches data as long as you have an api
key and then displays articles about bitcoin on the page. Try it out, and
see if it works. The env variable name is REACT_APP_API_KEY

**Comment by AseckOben** [comment]
Okay bro

**Comment by AseckOben** [comment]
Bro I will like us to do a zoom call tomorrow if you got chance , pls let
me know the time

**Comment by Landon345** [comment]
Sure, we can do a zoom call on Wednesday (tomorrow) at the same time as the
last one we did. 11AM for me and 6PM for you.

**Comment by AseckOben** [comment]
Thanks bro... Tomorrow then.
